export const countrys: {
    id: number;
    text: string;
    code: string;
    code_phone?: string;
    img?: string;
}[] = [
    {
        id: 144,
        text: "Afganistán",
        code: "AF",
        code_phone: "+93",
    },
    {
        id: 114,
        text: "Albania",
        code: "AL",
        code_phone: "+355",
    },
    {
        id: 18,
        text: "Alemania",
        code: "DE",
        code_phone: "+49",
    },
    {
        id: 98,
        text: "Argelia",
        code: "DZ",
        code_phone: "+213",
    },
    {
        id: 145,
        text: "Andorra",
        code: "AD",
        code_phone: "+376",
    },
    {
        id: 119,
        text: "Angola",
        code: "AO",
        code_phone: "+244",
    },
    {
        id: 4,
        text: "Anguila",
        code: "AI",
        code_phone: "+1",
    },
    {
        id: 147,
        text: "Antigua y Barbuda",
        code: "AG",
        code_phone: "+1",
    },
    {
        id: 207,
        text: "Antillas Holandesas",
        code: "AN",
        code_phone: "+599",
    },
    {
        id: 91,
        text: "Arabia Saudita",
        code: "SA",
        code_phone: "+966",
    },
    {
        id: 5,
        text: "Argentina",
        code: "AR",
        code_phone: "+54",
    },
    {
        id: 6,
        text: "Armenia",
        code: "AM",
        code_phone: "+374",
    },
    {
        id: 142,
        text: "Aruba",
        code: "AW",
        code_phone: "+297",
    },
    {
        id: 1,
        text: "Australia",
        code: "AU",
        code_phone: "+61",
    },
    {
        id: 2,
        text: "Austria",
        code: "AT",
        code_phone: "+43",
    },
    {
        id: 3,
        text: "Azerbaiyán",
        code: "AZ",
        code_phone: "+994",
    },
    {
        id: 80,
        text: "Bahamas",
        code: "BS",
        code_phone: "+1",
    },
    {
        id: 127,
        text: "Baréin",
        code: "BH",
        code_phone: "+973",
    },
    {
        id: 149,
        text: "Bangladesh",
        code: "BD",
        code_phone: "+880",
    },
    {
        id: 128,
        text: "Barbados",
        code: "BB",
        code_phone: "+1",
    },
    {
        id: 9,
        text: "Bélgica",
        code: "BE",
        code_phone: "+32",
    },
    {
        id: 8,
        text: "Belice",
        code: "BZ",
        code_phone: "+501",
    },
    {
        id: 151,
        text: "Benín",
        code: "BJ",
        code_phone: "+229",
    },
    {
        id: 10,
        text: "Bermudas",
        code: "BM",
        code_phone: "+1",
    },
    {
        id: 7,
        text: "Bielorrusia",
        code: "BY",
        code_phone: "+375",
    },
    {
        id: 123,
        text: "Bolivia",
        code: "BO",
        code_phone: "+591",
    },
    {
        id: 79,
        text: "Bosnia y Herzegovina",
        code: "BA",
        code_phone: "+387",
    },
    {
        id: 100,
        text: "Botsuana",
        code: "BW",
        code_phone: "+267",
    },
    {
        id: 12,
        text: "Brasil",
        code: "BR",
        code_phone: "+55",
    },
    {
        id: 155,
        text: "Brunéi",
        code: "BN",
        code_phone: "+673",
    },
    {
        id: 11,
        text: "Bulgaria",
        code: "BG",
        code_phone: "+359",
    },
    {
        id: 156,
        text: "Burkina Faso",
        code: "BF",
        code_phone: "+226",
    },
    {
        id: 157,
        text: "Burundi",
        code: "BI",
        code_phone: "+257",
    },
    {
        id: 152,
        text: "Bután",
        code: "BT",
        code_phone: "+975",
    },
    {
        id: 159,
        text: "Cabo Verde",
        code: "CV",
        code_phone: "+238",
    },
    {
        id: 158,
        text: "Camboya",
        code: "KH",
        code_phone: "+855",
    },
    {
        id: 31,
        text: "Camerún",
        code: "CM",
        code_phone: "+237",
    },
    {
        id: 32,
        text: "Canadá",
        code: "CA",
        code_phone: "+1",
    },
    {
        id: 130,
        text: "Chad",
        code: "TD",
        code_phone: "+235",
    },
    {
        id: 81,
        text: "Chile",
        code: "CL",
        code_phone: "+56",
    },
    {
        id: 35,
        text: "China",
        code: "CN",
        code_phone: "+86",
    },
    {
        id: 33,
        text: "Chipre",
        code: "CY",
        code_phone: "+357",
    },
    {
        id: 82,
        text: "Colombia",
        code: "CO",
        code_phone: "+57",
    },
    {
        id: 164,
        text: "Comores",
        code: "KM",
        code_phone: "+269",
    },
    {
        id: 112,
        text: "Congo (Brazzaville)",
        code: "CG",
        code_phone: "+242",
    },
    {
        id: 165,
        text: "Congo (Kinshasa)",
        code: "CD",
        code_phone: "+243",
    },
    {
        id: 166,
        text: "Cook, Islas",
        code: "CK",
        code_phone: "+682",
    },
    {
        id: 84,
        text: "Corea del Norte",
        code: "KP",
        code_phone: "+850",
    },
    {
        id: 69,
        text: "Corea del Sur",
        code: "KR",
        code_phone: "+82",
    },
    {
        id: 168,
        text: "Costa de Marfil",
        code: "CI",
        code_phone: "+225",
    },
    {
        id: 36,
        text: "Costa Rica",
        code: "CR",
        code_phone: "+506",
    },
    {
        id: 71,
        text: "Croacia",
        code: "HR",
        code_phone: "+385",
    },
    {
        id: 113,
        text: "Cuba",
        code: "CU",
        code_phone: "+53",
    },
    {
        id: 22,
        text: "Dinamarca",
        code: "DK",
        code_phone: "+45",
    },
    {
        id: 169,
        text: "Djibouti, Yibuti",
        code: "DJ",
        code_phone: "+253",
    },
    {
        id: 103,
        text: "Ecuador",
        code: "EC",
        code_phone: "+593",
    },
    {
        id: 23,
        text: "Egipto",
        code: "EG",
        code_phone: "+20",
    },
    {
        id: 51,
        text: "El Salvador",
        code: "SV",
        code_phone: "+503",
    },
    {
        id: 93,
        text: "Emiratos Árabes Unidos",
        code: "AE",
        code_phone: "+971",
    },
    {
        id: 173,
        text: "Eritrea",
        code: "ER",
        code_phone: "+291",
    },
    {
        id: 52,
        text: "Eslovaquia",
        code: "SK",
        code_phone: "+421",
    },
    {
        id: 53,
        text: "Eslovenia",
        code: "SI",
        code_phone: "+386",
    },
    {
        id: 28,
        text: "España",
        code: "ES",
        code_phone: "+34",
    },
    {
        id: 55,
        text: "Estados Unidos",
        code: "US",
        code_phone: "+1",
    },
    {
        id: 68,
        text: "Estonia",
        code: "EE",
        code_phone: "+372",
    },
    {
        id: 121,
        text: "Etiopía",
        code: "ET",
        code_phone: "+251",
    },
    {
        id: 175,
        text: "Feroe, Islas",
        code: "FO",
        code_phone: "+298",
    },
    {
        id: 90,
        text: "Filipinas",
        code: "PH",
        code_phone: "+63",
    },
    {
        id: 63,
        text: "Finlandia",
        code: "FI",
        code_phone: "+358",
    },
    {
        id: 176,
        text: "Fiyi",
        code: "FJ",
        code_phone: "+679",
    },
    {
        id: 64,
        text: "Francia",
        code: "FR",
        code_phone: "+33",
    },
    {
        id: 180,
        text: "Gabón",
        code: "GA",
        code_phone: "+241",
    },
    {
        id: 181,
        text: "Gambia",
        code: "GM",
        code_phone: "+220",
    },
    {
        id: 21,
        text: "Georgia",
        code: "GE",
        code_phone: "+995",
    },
    {
        id: 105,
        text: "Ghana",
        code: "GH",
        code_phone: "+233",
    },
    {
        id: 143,
        text: "Gibraltar",
        code: "GI",
        code_phone: "+350",
    },
    {
        id: 184,
        text: "Granada",
        code: "GD",
        code_phone: "+1",
    },
    {
        id: 20,
        text: "Grecia",
        code: "GR",
        code_phone: "+30",
    },
    {
        id: 94,
        text: "Groenlandia",
        code: "GL",
        code_phone: "+299",
    },
    {
        id: 17,
        text: "Guadalupe",
        code: "GP",
        code_phone: "+590",
    },
    {
        id: 185,
        text: "Guatemala",
        code: "GT",
        code_phone: "+502",
    },
    {
        id: 186,
        text: "Guernsey",
        code: "GG",
        code_phone: "+44",
    },
    {
        id: 187,
        text: "Guinea",
        code: "GN",
        code_phone: "+224",
    },
    {
        id: 172,
        text: "Guinea Ecuatorial",
        code: "GQ",
        code_phone: "+240",
    },
    {
        id: 188,
        text: "Guinea-Bissau",
        code: "GW",
        code_phone: "+245",
    },
    {
        id: 189,
        text: "Guyana",
        code: "GY",
        code_phone: "+592",
    },
    {
        id: 16,
        text: "Haiti",
        code: "HT",
        code_phone: "+509",
    },
    {
        id: 137,
        text: "Honduras",
        code: "HN",
        code_phone: "+504",
    },
    {
        id: 73,
        text: "Hong Kong",
        code: "HK",
        code_phone: "+852",
    },
    {
        id: 14,
        text: "Hungría",
        code: "HU",
        code_phone: "+36",
    },
    {
        id: 25,
        text: "India",
        code: "IN",
        code_phone: "+91",
    },
    {
        id: 74,
        text: "Indonesia",
        code: "ID",
        code_phone: "+62",
    },
    {
        id: 140,
        text: "Irak",
        code: "IQ",
        code_phone: "+964",
    },
    {
        id: 26,
        text: "Irán",
        code: "IR",
        code_phone: "+98",
    },
    {
        id: 27,
        text: "Irlanda",
        code: "IE",
        code_phone: "+353",
    },
    {
        id: 215,
        text: "Isla Pitcairn",
        code: "PN",
        code_phone: "+64",
    },
    {
        id: 83,
        text: "Islandia",
        code: "IS",
        code_phone: "+354",
    },
    {
        id: 228,
        text: "Islas Salomón",
        code: "SB",
        code_phone: "+677",
    },
    {
        id: 58,
        text: "Islas Turcas y Caicos",
        code: "TC",
        code_phone: "+1",
    },
    {
        id: 154,
        text: "Islas Vírgenes Británicas",
        code: "VG",
        code_phone: "+1",
    },
    {
        id: 24,
        text: "Israel",
        code: "IL",
        code_phone: "+972",
    },
    {
        id: 29,
        text: "Italia",
        code: "IT",
        code_phone: "+39",
    },
    {
        id: 132,
        text: "Jamaica",
        code: "JM",
        code_phone: "+1",
    },
    {
        id: 70,
        text: "Japón",
        code: "JP",
        code_phone: "+81",
    },
    {
        id: 193,
        text: "Jersey",
        code: "JE",
        code_phone: "+44",
    },
    {
        id: 75,
        text: "Jordania",
        code: "JO",
        code_phone: "+962",
    },
    {
        id: 30,
        text: "Kazajstán",
        code: "KZ",
        code_phone: "+7",
    },
    {
        id: 97,
        text: "Kenia",
        code: "KE",
        code_phone: "+254",
    },
    {
        id: 34,
        text: "Kirguistán",
        code: "KG",
        code_phone: "+996",
    },
    {
        id: 195,
        text: "Kiribati",
        code: "KI",
        code_phone: "+686",
    },
    {
        id: 37,
        text: "Kuwait",
        code: "KW",
        code_phone: "+965",
    },
    {
        id: 196,
        text: "Laos",
        code: "LA",
        code_phone: "+856",
    },
    {
        id: 197,
        text: "Lesotho",
        code: "LS",
        code_phone: "+266",
    },
    {
        id: 38,
        text: "Letonia",
        code: "LV",
        code_phone: "+371",
    },
    {
        id: 99,
        text: "Líbano",
        code: "LB",
        code_phone: "+961",
    },
    {
        id: 198,
        text: "Liberia",
        code: "LR",
        code_phone: "+231",
    },
    {
        id: 39,
        text: "Libia",
        code: "LY",
        code_phone: "+218",
    },
    {
        id: 126,
        text: "Liechtenstein",
        code: "LI",
        code_phone: "+423",
    },
    {
        id: 40,
        text: "Lituania",
        code: "LT",
        code_phone: "+370",
    },
    {
        id: 41,
        text: "Luxemburgo",
        code: "LU",
        code_phone: "+352",
    },
    {
        id: 85,
        text: "Macedonia",
        code: "MK",
        code_phone: "+389",
    },
    {
        id: 134,
        text: "Madagascar",
        code: "MG",
        code_phone: "+261",
    },
    {
        id: 76,
        text: "Malasia",
        code: "MY",
        code_phone: "+60",
    },
    {
        id: 125,
        text: "Malaui",
        code: "MW",
        code_phone: "+265",
    },
    {
        id: 200,
        text: "Maldivas",
        code: "MV",
        code_phone: "+960",
    },
    {
        id: 133,
        text: "Malí",
        code: "ML",
        code_phone: "+223",
    },
    {
        id: 86,
        text: "Malta",
        code: "MT",
        code_phone: "+356",
    },
    {
        id: 131,
        text: "Isla de Man",
        code: "IM",
        code_phone: "+44",
    },
    {
        id: 104,
        text: "Marruecos",
        code: "MA",
        code_phone: "+212",
    },
    {
        id: 201,
        text: "Martinica",
        code: "MQ",
        code_phone: "+596",
    },
    {
        id: 202,
        text: "Mauricio",
        code: "MU",
        code_phone: "+230",
    },
    {
        id: 108,
        text: "Mauritania",
        code: "MR",
        code_phone: "+222",
    },
    {
        id: 42,
        text: "México",
        code: "MX",
        code_phone: "+52",
    },
    {
        id: 43,
        text: "Moldavia",
        code: "MD",
        code_phone: "+373",
    },
    {
        id: 44,
        text: "Mónaco",
        code: "MC",
        code_phone: "+377",
    },
    {
        id: 139,
        text: "Mongolia",
        code: "MN",
        code_phone: "+976",
    },
    {
        id: 117,
        text: "Mozambique",
        code: "MZ",
        code_phone: "+258",
    },
    {
        id: 205,
        text: "Myanmar",
        code: "MM",
        code_phone: "+95",
    },
    {
        id: 102,
        text: "Namibia",
        code: "NA",
        code_phone: "+264",
    },
    {
        id: 206,
        text: "Nauru",
        code: "NR",
        code_phone: "+674",
    },
    {
        id: 107,
        text: "Nepal",
        code: "NP",
        code_phone: "+977",
    },
    {
        id: 209,
        text: "Nicaragua",
        code: "NI",
        code_phone: "+505",
    },
    {
        id: 210,
        text: "Níger",
        code: "NE",
        code_phone: "+227",
    },
    {
        id: 115,
        text: "Nigeria",
        code: "NG",
        code_phone: "+234",
    },
    {
        id: 212,
        text: "Norfolk Island",
        code: "NF",
        code_phone: "+672",
    },
    {
        id: 46,
        text: "Noruega",
        code: "NO",
        code_phone: "+47",
    },
    {
        id: 208,
        text: "Nueva Caledonia",
        code: "NC",
        code_phone: "+687",
    },
    {
        id: 45,
        text: "Nueva Zelanda",
        code: "NZ",
        code_phone: "+64",
    },
    {
        id: 213,
        text: "Omán",
        code: "OM",
        code_phone: "+968",
    },
    {
        id: 19,
        text: "Países Bajos, Holanda",
        code: "NL",
        code_phone: "+31",
    },
    {
        id: 87,
        text: "Pakistán",
        code: "PK",
        code_phone: "+92",
    },
    {
        id: 124,
        text: "Panamá",
        code: "PA",
        code_phone: "+507",
    },
    {
        id: 88,
        text: "Papúa-Nueva Guinea",
        code: "PG",
        code_phone: "+675",
    },
    {
        id: 110,
        text: "Paraguay",
        code: "PY",
        code_phone: "+595",
    },
    {
        id: 89,
        text: "Perú",
        code: "PE",
        code_phone: "+51",
    },
    {
        id: 178,
        text: "Polinesia Francesa",
        code: "PF",
        code_phone: "+689",
    },
    {
        id: 47,
        text: "Polonia",
        code: "PL",
        code_phone: "+48",
    },
    {
        id: 48,
        text: "Portugal",
        code: "PT",
        code_phone: "+351",
    },
    {
        id: 246,
        text: "Puerto Rico",
        code: "PR",
        code_phone: "+1",
    },
    {
        id: 216,
        text: "Qatar",
        code: "QA",
        code_phone: "+974",
    },
    {
        id: 13,
        text: "Reino Unido",
        code: "GB",
        code_phone: "+44",
    },
    {
        id: 65,
        text: "República Checa",
        code: "CZ",
        code_phone: "+420",
    },
    {
        id: 138,
        text: "República Dominicana",
        code: "DO",
        code_phone: "+1",
    },
    {
        id: 49,
        text: "Reunión",
        code: "RE",
        code_phone: "+262",
    },
    {
        id: 217,
        text: "Ruanda",
        code: "RW",
        code_phone: "+250",
    },
    {
        id: 72,
        text: "Rumanía",
        code: "RO",
        code_phone: "+40",
    },
    {
        id: 50,
        text: "Rusia",
        code: "RU",
        code_phone: "+7",
    },
    {
        id: 242,
        text: "Sáhara Occidental",
        code: "EH",
        code_phone: "+212",
    },
    {
        id: 223,
        text: "Samoa",
        code: "WS",
        code_phone: "+685",
    },
    {
        id: 219,
        text: "San Cristóbal y Nieves",
        code: "KN",
        code_phone: "+1",
    },
    {
        id: 224,
        text: "San Marino",
        code: "SM",
        code_phone: "+378",
    },
    {
        id: 221,
        text: "San Pedro y Miquelón",
        code: "PM",
        code_phone: "+508",
    },
    {
        id: 225,
        text: "San Tomé y Príncipe",
        code: "ST",
        code_phone: "+239",
    },
    {
        id: 222,
        text: "San Vicente y las Granadinas",
        code: "VC",
        code_phone: "+1",
    },
    {
        id: 218,
        text: "Santa Elena",
        code: "SH",
        code_phone: "+290",
    },
    {
        id: 220,
        text: "Santa Lucía",
        code: "LC",
        code_phone: "+1",
    },
    {
        id: 135,
        text: "Senegal",
        code: "SN",
        code_phone: "+221",
    },
    {
        id: 226,
        text: "Serbia y Montenegro",
        code: "CS",
        code_phone: "+381",
    },
    {
        id: 109,
        text: "Seychelles",
        code: "SC",
        code_phone: "+248",
    },
    {
        id: 227,
        text: "Sierra Leona",
        code: "SL",
        code_phone: "+232",
    },
    {
        id: 77,
        text: "Singapur",
        code: "SG",
        code_phone: "+65",
    },
    {
        id: 106,
        text: "Siria",
        code: "SY",
        code_phone: "+963",
    },
    {
        id: 229,
        text: "Somalia",
        code: "SO",
        code_phone: "+252",
    },
    {
        id: 120,
        text: "Sri Lanka",
        code: "LK",
        code_phone: "+94",
    },
    {
        id: 141,
        text: "Sudáfrica",
        code: "ZA",
        code_phone: "+27",
    },
    {
        id: 232,
        text: "Sudán",
        code: "SD",
        code_phone: "+249",
    },
    {
        id: 67,
        text: "Suecia",
        code: "SE",
        code_phone: "+46",
    },
    {
        id: 66,
        text: "Suiza",
        code: "CH",
        code_phone: "+41",
    },
    {
        id: 54,
        text: "Surinam",
        code: "SR",
        code_phone: "+597",
    },
    {
        id: 234,
        text: "Suazilandia",
        code: "SZ",
        code_phone: "+268",
    },
    {
        id: 56,
        text: "Tayikistán",
        code: "TJ",
        code_phone: "+992",
    },
    {
        id: 92,
        text: "Tailandia",
        code: "TH",
        code_phone: "+66",
    },
    {
        id: 78,
        text: "Taiwán",
        code: "TW",
        code_phone: "+886",
    },
    {
        id: 101,
        text: "Tanzania",
        code: "TZ",
        code_phone: "+255",
    },
    {
        id: 171,
        text: "Timor Oriental",
        code: "TL",
        code_phone: "+670",
    },
    {
        id: 136,
        text: "Togo",
        code: "TG",
        code_phone: "+228",
    },
    {
        id: 235,
        text: "Tokelau",
        code: "TK",
        code_phone: "+690",
    },
    {
        id: 236,
        text: "Tonga",
        code: "TO",
        code_phone: "+676",
    },
    {
        id: 237,
        text: "Trinidad y Tobago",
        code: "TT",
        code_phone: "+1",
    },
    {
        id: 122,
        text: "Túnez",
        code: "TN",
        code_phone: "+216",
    },
    {
        id: 57,
        text: "Turkmenistán",
        code: "TM",
        code_phone: "+993",
    },
    {
        id: 59,
        text: "Turquía",
        code: "TR",
        code_phone: "+90",
    },
    {
        id: 239,
        text: "Tuvalu",
        code: "TV",
        code_phone: "+688",
    },
    {
        id: 62,
        text: "Ucrania",
        code: "UA",
        code_phone: "+380",
    },
    {
        id: 60,
        text: "Uganda",
        code: "UG",
        code_phone: "+256",
    },
    {
        id: 111,
        text: "Uruguay",
        code: "UY",
        code_phone: "+598",
    },
    {
        id: 61,
        text: "Uzbekistán",
        code: "UZ",
        code_phone: "+998",
    },
    {
        id: 240,
        text: "Vanuatu",
        code: "VU",
        code_phone: "+678",
    },
    {
        id: 95,
        text: "Venezuela",
        code: "VE",
        code_phone: "+58",
    },
    {
        id: 15,
        text: "Vietnam",
        code: "VN",
        code_phone: "+84",
    },
    {
        id: 241,
        text: "Wallis y Futuna",
        code: "WF",
        code_phone: "+681",
    },
    {
        id: 243,
        text: "Yemen",
        code: "YE",
        code_phone: "+967",
    },
    {
        id: 116,
        text: "Zambia",
        code: "ZM",
        code_phone: "+260",
    },
    {
        id: 96,
        text: "Zimbabue",
        code: "ZW",
        code_phone: "+263",
    },
    {
        id: 247,
        text: "Bonaire",
        code: "BON",
        code_phone: "+599",
    },
    {
        id: 248,
        text: "Curazao",
        code: "CUR",
        code_phone: "+599",
    },
    {
        id: 249,
        text: "Chipre",
        code: "CHI",
        code_phone: "+357",
    },
];
