import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/Theme-provider";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/toaster";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import DashboardClient from "@/components/DashboardClient";
import AuthProviders from "@/components/providers/Auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Resume Maker ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="" id="remove-bg">
      <body className={inter.className} id="remove-bg">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProviders>
            <DashboardClient />
            {children}
          </AuthProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
